name: Multiple Jobs

on: [workflow_dispatch]

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
        
            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
            
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.3.6
              with:
                name: dragon-text-file
                path: dragon.txt
          

    test_job_1:
        needs: [build_job_1]
        runs-on: ubuntu-latest
        steps:
            - name: Download a Build Artifact
              uses: actions/download-artifact@v4.1.8
              with:
                name: dragon-text-file
        
            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
            
            - name: sleep for 30 sec
              run: sleep 30s

    deploy_job_3:
        needs: [test_job_1]
        concurrency: 
            group: deploy_job
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: Download a Build Artifact
              uses: actions/download-artifact@v4.1.8
              with:
                name: dragon-text-file
        
            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying...



